<?php
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\LabTechnicianController;
use App\Http\Controllers\PathologistController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\TestBookingController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TestReportController;
use App\Http\Controllers\TestResultController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\TestPackageController;
use App\Services\PDF\DirectPDFGenerator;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\StaffController;

// Public authentication routes
Route::post('register', [AuthController::class, 'register']);
Route::post('login', [AuthController::class, 'login']);

// Test route for PDF generation
Route::get('/test-pdf', function() {
    try {
        $html = '<h1>Test PDF</h1><p>This is a test PDF generated by DomPDF</p>';
        $dompdf = DirectPDFGenerator::fromHtml($html);
        
        return response($dompdf->output())
            ->header('Content-Type', 'application/pdf')
            ->header('Content-Disposition', 'attachment; filename="test.pdf"');
    } catch (\Exception $e) {
        return response()->json([
            'error' => $e->getMessage(),
            'trace' => $e->getTraceAsString()
        ], 500);
    }
});

// Protected routes using Sanctum
Route::middleware('auth:sanctum')->group(function () {
    // User info route
    Route::get('user', [AuthController::class, 'user']);

    Route::post('logout', [AuthController::class, 'logout']);
    
    // User roles
    Route::apiResource('patients', PatientController::class);
    Route::get('/patients/current', [PatientController::class, 'current']);
    Route::apiResource('lab-technicians', LabTechnicianController::class);
    // Route::apiResource('pathologists', PathologistController::class);
    Route::apiResource('doctors', DoctorController::class);
    Route::get('/doctors/current', [DoctorController::class, 'current']);

    Route::apiResource('staffs', StaffController::class);
    Route::get('/staffs/search', [StaffController::class, 'search']);
    Route::get('/staff-roles', [StaffController::class, 'getRoles']);


    // Test Templates routes
    Route::get('/test-templates', [TestController::class, 'getAllTestTemplates']);
    Route::get('/test-template/{id}', [TestController::class, 'getTestTemplate']);
    Route::post('/test-template', [TestController::class, 'createTestTemplate']);
    Route::put('/test-template/{id}', [TestController::class, 'updateTestTemplate']);
    Route::delete('/test-template/{id}', [TestController::class, 'deleteTestTemplate']);
    Route::get('/test-templates/{id}', [TestController::class, 'show']);

    // Test-related routes
    Route::get('/test-categories', [TestController::class, 'getCategories']);
    
    Route::middleware('auth:sanctum')->group(function () {
        Route::apiResource('test-bookings', TestBookingController::class);
        Route::post('/test-bookings/{testBooking}/mark-sample-collected', [TestBookingController::class, 'markSampleCollected']);
        Route::post('/test-bookings/{testBooking}/mark-processing', [TestBookingController::class, 'markProcessing']);
        Route::post('/test-bookings/{testBooking}/mark-reviewed', [TestBookingController::class, 'markReviewed']);
        Route::post('/test-bookings/{testBooking}/mark-completed', [TestBookingController::class, 'markCompleted']);
        Route::post('/test-bookings/{testBooking}/cancel', [TestBookingController::class, 'cancel']);
    });

    // Test Report Routes
    Route::get('/reports', [TestReportController::class, 'index']);
    Route::post('/test-bookings/{testBooking}/reports', [TestReportController::class, 'store']);
    Route::post('/reports/{testReport}/submit', [TestReportController::class, 'submit']);
    Route::post('/reports/{testReport}/review', [TestReportController::class, 'review']);
    Route::post('/reports/{testReport}/validate', [TestReportController::class, 'validate']);
    Route::post('/reports/{testReport}/reject', [TestReportController::class, 'reject']);
    Route::get('/reports/{testReport}/download', [TestReportController::class, 'download']);
    Route::post('/reports/{testReport}/notify', [TestReportController::class, 'notify']);

    // Test Result Routes
    Route::post('/test-reports/{testReport}/validate-results', [TestResultController::class, 'validateResults']);
    Route::get('/test-parameters/{parameter}/reference-ranges', [TestResultController::class, 'getParameterReferenceRanges']);
    Route::get('/test-results/statistics', [TestResultController::class, 'calculateStatistics']);

    // Test Packages Routes
    Route::get('/test-packages', [TestPackageController::class, 'index']);
    Route::post('/test-packages', [TestPackageController::class, 'store']);
    Route::get('/test-packages/{testPackage}', [TestPackageController::class, 'show']);
    Route::put('/test-packages/{testPackage}', [TestPackageController::class, 'update']);
    Route::delete('/test-packages/{testPackage}', [TestPackageController::class, 'destroy']);

    // Helper route to get available tests for packages
    Route::get('/available-tests', [TestPackageController::class, 'getAvailableTests']);

    // Dashboard Stats Routes
    Route::get('/admin/dashboard-stats', [DashboardController::class, 'adminStats']);
    Route::get('/doctor/dashboard-stats', [DashboardController::class, 'doctorStats']);
    Route::get('/lab/dashboard-stats', [DashboardController::class, 'labStats']);
    Route::get('/patient/dashboard-stats', [DashboardController::class, 'patientStats']);
});

